-- 1. Create and select the database
CREATE DATABASE IF NOT EXISTS CFOSDB;
USE CFOSDB;

-- 2. Drop tables in reverse order of dependencies to avoid constraint issues
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Tbl_Payment;
DROP TABLE IF EXISTS Tbl_OrderItem;
DROP TABLE IF EXISTS Tbl_Order;
DROP TABLE IF EXISTS Tbl_Food;
DROP TABLE IF EXISTS Tbl_FoodCategory;
DROP TABLE IF EXISTS Tbl_RolePermission;
DROP TABLE IF EXISTS Tbl_Permission;
DROP TABLE IF EXISTS Tbl_User;
DROP TABLE IF EXISTS Tbl_Role;
SET FOREIGN_KEY_CHECKS = 1;

-- 3. Create Tables
CREATE TABLE Tbl_Role (
    RoleID INT PRIMARY KEY AUTO_INCREMENT,
    RoleName VARCHAR(50) NOT NULL UNIQUE,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Tbl_User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    RoleID INT NOT NULL,
    UserName VARCHAR(30) NOT NULL UNIQUE,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    PasswordHash VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20),
    Status VARCHAR(20) NOT NULL,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (RoleID) REFERENCES Tbl_Role(RoleID)
);

CREATE TABLE Tbl_Permission (
    PermissionID INT PRIMARY KEY AUTO_INCREMENT,
    MenuName VARCHAR(50) NOT NULL,
    ActionName VARCHAR(20) NOT NULL,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Tbl_RolePermission (
    RolePermissionID INT PRIMARY KEY AUTO_INCREMENT,
    RoleID INT NOT NULL,
    PermissionID INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RoleID) REFERENCES Tbl_Role(RoleID),
    FOREIGN KEY (PermissionID) REFERENCES Tbl_Permission(PermissionID)
);

CREATE TABLE Tbl_FoodCategory (
    CategoryID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(100) NOT NULL,
    Description VARCHAR(255),
    CreatedBy INT NOT NULL,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CreatedBy) REFERENCES Tbl_User(UserID)
);

CREATE TABLE Tbl_Food (
    FoodID INT PRIMARY KEY AUTO_INCREMENT,
    CategoryID INT NOT NULL,
    FoodName VARCHAR(100) NOT NULL,
    Description TEXT,
    Price DECIMAL(10,2) NOT NULL,
    ImageURL VARCHAR(255),
    IsAvailable BOOLEAN DEFAULT TRUE,
    CreatedBy INT NOT NULL,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CategoryID) REFERENCES Tbl_FoodCategory(CategoryID),
    FOREIGN KEY (CreatedBy) REFERENCES Tbl_User(UserID)
);

CREATE TABLE Tbl_Order (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TotalAmount DECIMAL(10,2) NOT NULL,
    OrderStatus VARCHAR(30) NOT NULL,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Tbl_User(UserID)
);

CREATE TABLE Tbl_OrderItem (
    OrderItemID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL,
    FoodID INT NOT NULL,
    Quantity INT NOT NULL,
    SnapPrice DECIMAL(10,2) NOT NULL,
    SubTotal DECIMAL(10,2) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Tbl_Order(OrderID),
    FOREIGN KEY (FoodID) REFERENCES Tbl_Food(FoodID)
);

CREATE TABLE Tbl_Payment (
    PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL UNIQUE,
    Amount DECIMAL(10,2) NOT NULL,
    PaymentMethod VARCHAR(50),
    PaymentStatus VARCHAR(30),
    DeleteFlag BOOLEAN DEFAULT FALSE,
    PaidAt DATETIME,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Tbl_Order(OrderID)
);