USE CFOSDB;

CREATE TABLE IF NOT EXISTS Tbl_Review (
    ReviewID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Rating DOUBLE NOT NULL,
    ReviewText TEXT NOT NULL,
    DeleteFlag BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Tbl_User(UserID)
);
