USE CFOSDB;

ALTER TABLE Tbl_User
    ADD COLUMN CanteenID INT NULL AFTER RoleID;

ALTER TABLE Tbl_User
    ADD CONSTRAINT FK_User_Canteen
    FOREIGN KEY (CanteenID) REFERENCES Tbl_Canteen(BranchID)
    ON DELETE SET NULL
    ON UPDATE CASCADE;
